name: recast_designs_assessment
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  intl: ^0.19.0

  flutter_screenutil: ^5.9.3
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Light.ttf
    - family: Satoshi-Variable
      fonts:
        - asset: assets/fonts/Satoshi-Variable.ttf
          weight: 400
